#!/usr/bin/env bash
echo "Deleting Objects in the S3 bucket"

set -e

#Check for bucket name
if [ -z "$1" ]
then
  echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1

#Delete all the files/objects in the bucket
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query 'Contents[].{Key: Key}' \
--output text | while read line; do
  aws s3api delete-object \
  --bucket $BUCKET_NAME \
  --key $line
done