#!/usr/bin/env bash
echo "List Objects in a S3 bucket"
#Check if the first argument is provided
if [ -z "$1" ]
then
  echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
